### ISSUE TITLE
Google home resume error script

### ISSUE THREAD

**Issue by besiktas97** [TheFes/HA-configuration#89]
Hey TheFes,

I am getting since a couple of days the next error message:

Logger: homeassistant.components.script.1662498337269
Source: helpers/script.py:410 
Integration: Script (documentation, issues) 
First occurred: 17:50:02 (6 occurrences) 
Last logged: 17:50:07

00 - Google Home Resume - Helper Script: If at step 1: Error executing script. Error for wait_template at pos 1: In 'template' condition: TemplateError: Invalid domain name ''
00 - Google Home Resume - Helper Script: Error executing script. Error for if at pos 1: In 'template' condition: TemplateError: Invalid domain name ''

I didn't change anything further on script side and don't known why it isnt resuming anymore. 
Can you help me?

**Comment by TheFes** [comment]
Thanks, I'll have a look

**Comment by TheFes** [comment]
Could you send me a trace of the helper script?

**Comment by besiktas97** [comment]
Sure. 
[trace script.google_home_resume_helper 2023-05-10T11_43_00.459224+00_00.json.zip](https://github.com/TheFes/HA-configuration/files/11442436/trace.script.google_home_resume_helper.2023-05-10T11_43_00.459224%2B00_00.json.zip)

**Comment by TheFes** [comment]
This one had no errors
```json
{
  "trace": {
    "last_step": "sequence/0/then/10",
    "run_id": "3d5c6d475b280b64a203858ba77ab5d8",
    "state": "stopped",
    "script_execution": "finished",
    "timestamp": {
      "start": "2023-05-10T11:43:00.459224+00:00",
      "finish": "2023-05-10T11:46:06.887840+00:00"
    }
```

**Comment by besiktas97** [comment]
> This one had no errors
> 
> ```json
> 
> {
> 
>   "trace": {
> 
>     "last_step": "sequence/0/then/10",
> 
>     "run_id": "3d5c6d475b280b64a203858ba77ab5d8",
> 
>     "state": "stopped",
> 
>     "script_execution": "finished",
> 
>     "timestamp": {
> 
>       "start": "2023-05-10T11:43:00.459224+00:00",
> 
>       "finish": "2023-05-10T11:46:06.887840+00:00"
> 
>     }
> 
> ```

Strange that the log says that this one has a error and that the radio isnt resuming.

**Comment by besiktas97** [comment]
And now getting those errors, kinda strange. I think a update of HA has broken something:

Logger: homeassistant.helpers.template
Source: helpers/template.py:230
First occurred: 21:48:38 (2568 occurrences)
Last logged: 21:48:45

Template variable warning: 'str object' has no attribute 'members' when rendering '{{ player_data | selectattr('entity_id', 'in', player.members) | list }}'

---------------------------------------------------------------------------------------------------------------------------------------

Logger: homeassistant.helpers.template
Source: helpers/template.py:665
First occurred: 21:48:40 (9 occurrences)
Last logged: 21:48:45

Template variable warning: 'str object' has no attribute 'entity_id' when rendering '{{ event_script or ytube_resume or ( (states[player.entity_id].last_changed > as_datetime(start_time)) and expand([player.entity_id] + player.members) | selectattr('state', 'eq', 'playing') | list | count > 0 ) or ( state_attr(player.entity_id, 'media_content_id') is not none and ( 'jpg' in state_attr(player.entity_id, 'media_content_id') or 'jpeg' in state_attr(player.entity_id, 'media_content_id') or 'png' in state_attr(player.entity_id, 'media_content_id') ) ) }}'

------------------------------------------------------------------------------------------------------------------------------

Logger: homeassistant.components.script.1662498337269
Source: helpers/script.py:410
Integration: Script (documentation, issues)
First occurred: 21:48:41 (6 occurrences)
Last logged: 21:48:45

00 - Google Home Resume - Helper Script: If at step 1: Error executing script. Error for wait_template at pos 1: In 'template' condition: TemplateError: Invalid domain name ''
00 - Google Home Resume - Helper Script: Error executing script. Error for if at pos 1: In 'template' condition: TemplateError: Invalid domain name ''

**Comment by besiktas97** [comment]
And this is the trace of the script for resuming it (not the helper):

[trace script.1662498337270 2023-05-10T19_48_38.288716+00_00.json.zip](https://github.com/TheFes/HA-configuration/files/11445540/trace.script.1662498337270.2023-05-10T19_48_38.288716%2B00_00.json.zip)

Thanks again TheFes

**Comment by TheFes** [comment]
There are multiple traces shown, and you can see if they finalized, or if there was an error:
![image](https://github.com/TheFes/HA-configuration/assets/28803438/fc69f08e-0965-48db-a757-21aa69c4155a)
If the service calls marked as performed stop already at the top, it failed. I need a trace of one of those cases, not one where it succeeded.

If possible, I also need the trace of the main script of the same timel

You can navigate between the last 5 traces with the arrows

**Comment by besiktas97** [comment]
Thanks TheFes I will create a test scenario and will provide you with the information you need.

**Comment by besiktas97** [comment]
I have now 3 traces, 1 from the automation and the other 2 are the scripts: Main script and the helper script where it fails and not resumes the radio from that moment.
[Traces.zip](https://github.com/TheFes/HA-configuration/files/11453119/Traces.zip)

You need this time stamp for it: "2023-05-11 16:11:20.645526+02:00",

**Comment by TheFes** [comment]
Hi,

I see what the problem is, and I already solved that some version ago.
However, it looks like you are still using quite an old version.

If you upgrade to the latest version, it should be solved,

**Comment by besiktas97** [comment]
I did upgrade now to the latest version and its still not working. 
Radio's are playing well but when a file a triggered from the main automation and the mp3 is finished, the radio's arent resuming. 
Maybe I am the noob that can't figure it out.

Trace from the main resume script: https://www.dpaste.org/4637P
Trace form the resume script helper: https://www.dpaste.org/dgfpB

**Comment by TheFes** [comment]
Those traces don't show anything, they are just the configuration. Looks like the first trace after you changed the configuration

**Comment by besiktas97** [comment]
I just dont get it. I see that the automation isnt triggered and the main automation for playing the mp3 is called by the service media_player.play_media. I did removed every old scripts including in the main automation and still dont work :-(

**Comment by besiktas97** [comment]
trace of my automation that should trigger your script: https://www.dpaste.org/WeLZK

**Comment by TheFes** [comment]
This automation won't trigger the script, as you didn't use `announce: true` in your service call.
So the automation will ignore it, and won't start the script.

**Comment by besiktas97** [comment]
Do I need put the service call in the automation itself or in the script?

**Comment by TheFes** [comment]
The automation you've sent above is not mine, it is `automation.namaz` with the name `Thuis: Ezan`
In it you start playing an mp3 (after setting the volume).
In the service call to play the mp3, you should add `announce: true` if you want this to trigger the script.

**Comment by besiktas97** [comment]
Ik blijf het vreemd vinden dat het maar niet werkt. Heb alles gedaan wat er stond en ook de announce: true erbij gezet (automation wordt nu netjes getriggerd), echter wordt maar niet hervat...

Sorry dat ik je er iedere keer mee lastig van, ik waardeer echt je hulp.

https://www.dpaste.org/WCAUW

**Comment by TheFes** [comment]
Toen ik de name van je automation zag, had ik al zoiets van: "Volgens mij kan ik ook gewoon in het Nederlands antwoorden"

De automation stopt vanwege de eerste condition. Wat ik zou aanraden is om het resume script direct aan te roepen in je automation `Thuis: Ezan`

Dat kun je op de volgende manier doen:
```yaml
service: script.turn_on
target:
  entity_id: script.google_home_resume
data:
  variables:
    action:
      - service: media_player.play_media
        target:
          entity_id: media_player.alle_boxen
        data:
          media_content_id: "http://besiktas97.noip.me:8123/local/azan2.mp3"
          media_content_type: "music"
        extra:
          volume: 0.5
```

Als je het zo doet, start je zelf het resume script, dus kan er niets fout gaan bij de automation. Verder hoef je ook het volume niet te veranderen, dat doet het script voor je. Dit is dan dus de enige actie die nodig is in je automation.

**Comment by besiktas97** [comment]
hehe ja het schoot me laatst binnen dat jij ook Nederlands sprak en dat het toch wat makkelijker gaat dan in het Engels.
Schiet mij maar lek Martijn, ik begrijp er echt geen zak meer van. Ondanks dat ik bovenstaande heb gedaan wat je vroeg doet die het gewoon niet. Terwijl die het altijd heeft gedaan...

https://www.dpaste.org/SJh3P

**Comment by TheFes** [comment]
Zou je de traces van het resume script en helper script eens kunnen sturen nadat je deze automation uitvoert

**Comment by TheFes** [comment]
En wordt de mp3 wel gewoon afgespeeld met de gewijzigde automation?

**Comment by besiktas97** [comment]
> Zou je de traces van het resume script en helper script eens kunnen sturen nadat je deze automation uitvoert

Ja hoor kan ik doen en de mp3 wordt inderdaad netjes afgespeeld op alle boxjes.

https://www.dpaste.org/gNi7Z -> Resume script
https://www.dpaste.org/rqXRj -> Helper script

De helper script heeft helemaal niet gedraaid zie ik nu ook net. Laatste keer was 11 uurtjes geleden, ondanks dat ik vandaag de automation handmatig hebt gedraaid.

**Comment by TheFes** [comment]
Er gaat inderdaad iets mis, de `target_list` is leeg. Ik ga even kijken wat hier mis gaat, want dit zou gewoon moeten werken.

**Comment by besiktas97** [comment]
> Er gaat inderdaad iets mis, de `target_list` is leeg. Ik ga even kijken wat hier mis gaat, want dit zou gewoon moeten werken.

Dank je wel Martijn. Dacht dat ik gek was. Had alles al uitgepluisd en gedaan hoe het moest 🤣🤣

**Comment by TheFes** [comment]
Ik zie denk ik waar het fout gaat. Jouw speaker group (`media_player.alle_boxen`) is een groep aangemaakt in Home Assistant en niet in de Google Home app. Klopt dat?
Het script gaat voor `media_player.alle_boxen` uit van een Google Home groep, en vindt deze vervolgens niet als enitity in de cast integratie. Vandaar dat hij de `target_list` leeg houdt

**Comment by besiktas97** [comment]
Klopt inderdaad dat mijn speakergroep een groep is vanuit HA en niet via Google Home.
Zo heeft het voorheen altijd gewerkt en niet echt opgelet op dat punt dat het voortaan een groep moest zijn vanuit GH.
Ik ga ermee aan de slag kijken wat het nu gaat doen :) 
Nogmaals dank Martijn.

**Comment by besiktas97** [comment]
Het werkt Martijn! Je bent een held, thanks!!

**Comment by TheFes** [comment]
Top! Fijn dat het weer werkt
